---

- name: Reload iptables
  raw: /sbin/iptables-restore < {{ iptables_restore_file }}
  listen: "reload firewall"


- name: Reload ip6tables
  raw: /sbin/ip6tables-restore < {{ ip6tables_restore_file }}
  listen: "reload ip6 firewall"
